deploymentName: posts-service-deployment
serviceName: posts
appLabel: posts
appName: posts

replicaCount: 1

image:
  repository: dannguyenmessi/posts
  tag: v2

containerPort: 8090

service:
  type: ClusterIP
  port: 8090
  targetPort: 8090

appname_enabled: true
profile_enabled: true
config_enabled: true
resourceserver_enabled: false
oauth_openid_enabled: false
zipkin_enabled: true
kafka_enabled: true
minio_enabled: true
redis_enabled: true
pageniation_enabled: true
schedule_enabled: true
appBaseUrl_enabled: true
usersdb_enabled: false
postsdb_enabled: true
commentsdb_enabled: false
notificationsdb_enabled: false
reportsdb_enabled: true
redis_reactive_enabled: fals
loki_enabled: true
discoveryclient_kubernetes_enabled: true