server:
  port: 8072

spring:
  application:
    name: gatewayserver
  config:
    import: optional:configserver:http://localhost:8071
  profiles:
    active: "dev"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/forum
          jwk-set-uri: http://localhost:7080/realms/forum/protocol/openid-connect/certs

oauth:
  openId:
    url: http://localhost:7080/realms/forum/.well-known/openid-configuration


#  data:
#    redis:
#      connect-timeout: 2s
#      host: localhost
#      port: 6379
#      timeout: 1s


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    config-url: /api-docs/swagger-config
    urls:
      - url: /api-docs
        name: API Gateway Service
        display-name: API Gateway Service
      - url: /forum/users/api-docs
        name: Users Service
        display-name: Users Service
    oauth:
      client-id: forum-authentication
      client-secret: l2WiWQULnEFt9KrgySvFK03QtVf9K4DO
      ##client-secret: RTNNPLYDsNafVR3DRc19jlYGceMaga67
  enable-native-support: true

info:
  app:
    name: "gatewayserver"
    description: "Forum Gateway Server Application Microservices"
    version: "1.0.0"

logging:
  level:
    com:
      didan:
        microservices:
          gatewaysever: debug
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"