apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  type: ClusterIP
  ports:
    - port: 2181
      targetPort: 2181
      name: http
    - port: 2888
      targetPort: 2888
      name: http2
    - port: 3888
      targetPort: 3888
      name: http3