apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-log-service-deployment
  labels:
    app: minio-log
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-log
  template:
    metadata:
      labels:
        app: minio-log
    spec:
      containers:
        - name: minio-log
          image: dannguyenmessi/forum-minio-log:v1
          ports:
            - containerPort: 9000