services:
  keycloakdb:
    image: mysql:8.0
    container_name: keycloakdb
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloakdb
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: 17052002
    volumes:
      - ../data/keycloakdb:/var/lib/mysql
    networks:
      - didan

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: keycloak
    command: "start-dev"
    ports:
      - "7080:8080"
    environment:
      KC_HEALTH_ENABLE: true
      KEYCLOAK_ADMIN: didannguyen
      KEYCLOAK_ADMIN_PASSWORD: 17052002
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://keycloakdb:3306/keycloakdb
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: 17052002
    depends_on:
      - keycloakdb
    volumes:
      - ../data/keycloak:/opt/keycloak/data/
    networks:
      - didan

networks:
  didan:
    driver: bridge