server:
  port: 8070

spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:http://localhost:8071

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/euraka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram.http.server.requests: true
  observations:
    key-values:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      encoding: json
      connect-timeout: 3s
      read-timeout: 10s

logging:
  level:
    com:
      didan:
        forum:
          eureka_server: debug
  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"