apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui-service-deployment
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: dannguyenmessi/forum-kafka-ui:v1
          ports:
            - containerPort: 8080
          env:
          - name: KAFKA_CLUSTERS_0_NAME
            value: kafka
          - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
            value: kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9092
          - name: KAFKA_CLUSTERS_0_METRICS_PORT
            value: '9997'
          - name: DYNAMIC_CONFIG_ENABLED
            value: 'true'