apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      name: http
    - port: 9997
      targetPort: 9997
      name: http2
    - port: 29092
      targetPort: 29092
      name: http3