server:
  port: 8072

spring:
  application:
    name: gateway-server
#  config:
#    import: optional:configserver:http://localhost:8071
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${oauth.openId.server}/realms/forum
          jwk-set-uri: http://${oauth.openId.server}/realms/forum/protocol/openid-connect/certs
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
        enabled: true
        discovery-server-url: http://spring-cloud-kubernetes-discoveryserver:80/
      httpclient:
        connect-timeout: 10000 # Thoi gian toi da de ket noi toi service
        response-timeout: 10s # Thoi gian toi da de nhan phan hoi tu service

oauth:
  openId:
    server: localhost:7080
    url: http://${oauth.openId.server}/realms/forum/.well-known/openid-configuration

#  data:
#    redis:
#      connect-timeout: 2s
#      host: localhost
#      port: 6379
#      timeout: 1s

private:
  route: users/update,users/qrcode,posts/update,comments/update,votes/add,votes/revoke,posts/update,posts/report,posts/new,posts/delete,comments/create,votes/revoke,votes/add,comments/report,comments/delete,notifications/delete,notifications/mark,notifications/read,notifications/unread

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    config-url: /api-docs/swagger-config
    urls:
      - url: /api-docs
        name: API Gateway Service
        display-name: API Gateway Service
      - url: /forum/users/api-docs
        name: Users Service
        display-name: Users Service
      - url: /forum/posts/api-docs
        name: Posts Service
        display-name: Posts Service
      - url: /forum/comments/api-docs
        name: Comments Service
        display-name: Comments Service
      - url: /forum/notifications/api-docs
        name: Notification Service
        display-name: Notification Service
    oauth:
      client-id: forum-authentication
      client-secret: l2WiWQULnEFt9KrgySvFK03QtVf9K4DO
  enable-native-support: true

info:
  app:
    name: "gatewayserver"
    description: "Forum Gateway Server Application Microservices"
    version: "1.0.0"

logging:
  level:
    com:
      didan:
        microservices:
          gatewaysever: debug
  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"