server:
  port: 8072

spring:
  application:
    name: gateway-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${oauth.openId.server}/realms/forum
          jwk-set-uri: http://${oauth.openId.server}/realms/forum/protocol/openid-connect/certs
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
        enabled: true
        discovery-server-url: http://spring-cloud-kubernetes-discoveryserver:80/
      httpclient:
        connect-timeout: 15000 # Thoi gian toi da de ket noi toi service
        response-timeout: 20s # Thoi gian toi da de nhan phan hoi tu service
  data:
    redis:
      connect-timeout: 20s
      host: localhost
      port: 6379
      timeout: 10s

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8070/eureka/

oauth:
  openId:
    server: localhost:7080
    url: http://${oauth.openId.server}/realms/forum/.well-known/openid-configuration

private:
  route: users/update,users/qrcode,posts/update,comments/update,votes/add,votes/revoke,posts/update,posts/report,posts/new,posts/delete,comments/create,votes/revoke,votes/add,comments/report,comments/delete,notifications/delete,notifications/mark,notifications/read,notifications/unread,users/verify/reactivate,notifications/all

app:
  loki:
    url: http://localhost:3100/loki/api/v1/push
  api:
    url: http://localhost:8072

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram.http.server.requests: true
  observations:
    key-values:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      encoding: json
      connect-timeout: 3s
      read-timeout: 10s

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    config-url: /api-docs/swagger-config
    urls:
      - url: /api-docs
        name: API Gateway Service
        display-name: API Gateway Service
      - url: /forum/users/api-docs
        name: Users Service
        display-name: Users Service
      - url: /forum/posts/api-docs
        name: Posts Service
        display-name: Posts Service
      - url: /forum/comments/api-docs
        name: Comments Service
        display-name: Comments Service
      - url: /forum/notifications/api-docs
        name: Notification Service
        display-name: Notification Service
    oauth:
      client-id: forum-authentication
      client-secret: l2WiWQULnEFt9KrgySvFK03QtVf9K4DO
  enable-native-support: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 200
        permitted-number-of-calls-in-half-open-state: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s

info:
  app:
    name: "gatewayserver"
    description: "Forum Gateway Server Application Microservices"
    version: "1.0.0"

logging:
  level:
    com:
      didan:
        microservices:
          gatewaysever: debug
  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"
    correlation: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"