spring.cloud:
  gateway:
    discovery:
      locator:
        enabled: false
        lower-case-service-id: true
    httpclient:
      connect-timeout: 10000 # Thoi gian toi da de ket noi toi service
      response-timeout: 10s # Thoi gian toi da de nhan phan hoi tu service

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/