server:
  port: 8090

spring:
  application:
    name: posts
#  config:
#    import: optional:configserver:http://localhost:8071
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  datasource:
    postdb:
      url: jdbc:mysql://localhost:3306/forum_posts
      username: 'root'
      password: '17052002'
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        connection-timeout: 60000
        max-lifetime: 590000
    reportdb:
      url: jdbc:mysql://localhost:3306/forum_reports
      username: 'root'
      password: '17052002'
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        connection-timeout: 60000
        max-lifetime: 590000
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 30MB
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
        discovery-server-url: http://spring-cloud-kubernetes-discoveryserver:80/
    stream:
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        sendPostScore-out-0:
          destination: post-score
        listenPostScore-in-0:
          destination: post-score
          group: ${spring.application.name}
        deletePost-out-0:
          destination: post-delete
        commentAction-in-0:
          destination: comment-action
          group: ${spring.application.name}
        sendNotification-out-0:
          destination: event-notification
    function:
      definition: listenPostScore;commentAction

springdoc:
  api-docs:
    path: /posts/api-docs
  swagger-ui:
    path: /posts/swagger-ui

app:
  cache:
    redis:
      enabled: true
      host: localhost
      port: 6379
      timeoutSeconds: 60
      maxPoolSize: 8
      maxIdle: 8
      minIdle: 0
      password:
  pagination:
    defaultSize: 20
  schedule:
    fixedDelay:
      milliseconds: 300000
  baseUrl: http://localhost:8072/forum
  log:
    request:
      ignoreHeaders: authorization,x-session-id,x-envoy-decorator-operation,X-Request-Id,sessionid,X-User-Id
      extended:
        enabled: true

private:
  route: votes/add,votes/revoke,posts/update,posts/report,posts/new,posts/delete
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram.http.server.requests: true
  observations:
    key-values:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0

endpoints:
  shutdown:
    enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 200
        permitted-number-of-calls-in-half-open-state: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s

info:
  app:
    name: ${spring.application.name}
    description: "Forum posts application"
    version: "1.0.0"

logging:
  level:
    com:
      didan:
        forum:
          posts: debug
  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"
    correlation: "[[${spring.application.name},%X{traceId},%X{spanId}]"

minio:
  root:
    user: didannguyen
    password: 17052002
    endpoint: http://localhost:10000
  bucketName: ${spring.application.name}