server:
  port: 8080

spring:
  application:
    name: users
#  config:
#    import: optional:configserver:http://localhost:8071
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  datasource:
    userdb:
      url: jdbc:mysql://localhost:3306/forum_users
      username: 'root'
      password: '17052002'
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        connection-timeout: 60000
        max-lifetime: 590000
    reportdb:
      url: jdbc:mysql://localhost:3306/forum_reports
      username: 'root'
      password: '17052002'
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        connection-timeout: 60000
        max-lifetime: 590000
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 30MB
  security:
    user:
      name: didannguyen
      password: 17052002
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
        discovery-server-url: http://spring-cloud-kubernetes-discoveryserver:80/
    function:
      definition: listenUserEmail
    stream:
      bindings:
        sendUserEmail-out-0:
          destination: mail-register
        listenUserEmail-in-0:
          destination: mail-register
          group: ${spring.application.name}
        sendNotification-out-0:
          destination: event-notification
      kafka:
        binder:
          brokers:
            - localhost:9092

springdoc:
  api-docs:
    path: /users/api-docs
  swagger-ui:
    path: /users/swagger-ui

oauth:
  openId:
    server: localhost:7080
    url: http://${oauth.openId.server}/realms/forum/.well-known/openid-configuration

keycloak:
  management-user:
    realm: forum
    server: http://${oauth.openId.server}
    client-id: admin-cli
    grant-type: password
    name: didannguyen
    password: 17052002
    client-secret: l2WiWQULnEFt9KrgySvFK03QtVf9K4DO
  client:
    client-id: forum-authentication
    client-secret: l2WiWQULnEFt9KrgySvFK03QtVf9K4DO
    grant-type-login: password
    grant-type-logout: refresh_token
    token-url: http://${oauth.openId.server}/realms/forum/protocol/openid-connect/

sendgrid:
  apiKey: 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
  fromEmail: social-service@didan.id.vn
  fromName: Forum Admin
  templateId: d-cb3c0b3bb8514de7991b0f47b12f8a6e
  urlVerify: ${app.baseUrl}/users/verify/

app:
  cache:
    redis:
      enabled: true
      host: localhost
      port: 6379
      timeoutSeconds: 60
      maxPoolSize: 8
      maxIdle: 8
      minIdle: 0
      password: jfz74hpkdMFx6qTfjIZT4kOixxq9iFB6
  pagination:
    defaultSize: 10
  schedule:
    fixedDelay:
      milliseconds: 300000
  baseUrl: http://localhost:8072/forum
  log:
    request:
      ignoreHeaders: authorization,x-session-id,x-envoy-decorator-operation,X-Request-Id,sessionid,X-User-Id
      extended:
        enabled: true
  loki:
    url: http://localhost:3100/loki/api/v1/push


private:
  route: users/update,users/qrcode,users/report,users/verify/reactivate
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram.http.server.requests: true
  observations:
    key-values:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      encoding: json
      connect-timeout: 3s
      read-timeout: 10s

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: ${spring.application.name}
    description: "Forum users application"
    version: "1.0.0"

logging:
  level:
    com:
      didan:
        forum:
          users: debug
  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"
    correlation: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"

minio:
  root:
    user: didannguyen
    password: 17052002
    endpoint: http://localhost:10000
  bucketName: ${spring.application.name}