server:
  port: 8090

spring:
  application:
    name: posts
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: "dev"
  config:
    import: optional:configserver:http://localhost:8071
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 30MB

springdoc:
  api-docs:
    path: /posts/api-docs
  swagger-ui:
    path: /posts/swagger-ui

app:
  cache:
    redis:
      enabled: false
      host: localhost
      port: 6379
      timeoutSeconds: 60
      maxPoolSize: 8
      maxIdle: 8
      minIdle: 0
      password:

private:
  route: /votes/add,votes/revoke
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: ${spring.application.name}
    description: "Forum posts application"
    version: "1.0.0"

logging:
  level:
    com:
      didan:
        forum:
          users: debug
  pattern:
    level: "%5p [${spring.application.name},%X{Trace-Id},%X{Span-Id}]"

minio:
  access-key: didannguyen
  secret-key: 17052002
  endpoint: http://localhost:10000
  bucket-name: posts