apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo-service-deployment
  labels:
    app: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: dannguyenmessi/forum-tempo:v1
          ports:
            - containerPort: 3100
            - containerPort: 9411