apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  selector:
    app: tempo
  type: ClusterIP
  ports:
    - port: 3110
      targetPort: 3100
      name: http
    - port: 9411
      targetPort: 9411
      name: http2