deploymentName: users-service-deployment
serviceName: users
appLabel: users
appName: users

replicaCount: 1

image:
  repository: dannguyenmessi/forum-users
  tag: v2

containerPort: 8080

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

appname_enabled: true
profile_enabled: true
config_enabled: true
resourceserver_enabled: false
oauth_openid_enabled: true
zipkin_enabled: true
kafka_enabled: true
minio_enabled: true
redis_enabled: true
pageniation_enabled: true
schedule_enabled: true
appBaseUrl_enabled: true
usersdb_enabled: true
postsdb_enabled: false
commentsdb_enabled: false
notificationsdb_enabled: false
reportsdb_enabled: true
redis_reactive_enabled: false
loki_enabled: true
discoveryclient_kubernetes_enabled: true