apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-service-deployment
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: dannguyenmessi/forum-prometheus:v1
          ports:
            - containerPort: 9090