FROM grafana/loki:3.0.0

LABEL authors="dannguyenmessi"

COPY loki-config.yaml /etc/loki/config.yaml

CMD ["-config.file=/etc/loki/config.yaml", "-target=backend", "-legacy-read-mode=false"]

EXPOSE 3100 7946