apiVersion: apps/v1
kind: Deployment
metadata:
  name: read-service-deployment
  labels:
    app: read
spec:
  replicas: 1
  selector:
    matchLabels:
      app: read
  template:
    metadata:
      labels:
        app: read
    spec:
      containers:
        - name: read
          image: dannguyenmessi/forum-read-loki:v1
          ports:
            - containerPort: 3100
            - containerPort: 9095
            - containerPort: 7946