global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'users'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'users-service:8080' ]
  - job_name: 'posts'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'posts-service:8090' ]
  - job_name: 'comments'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'comments-service:9000' ]
  - job_name: 'gateway-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gatewayserver:8072' ]
  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eurekaserver:8070' ]
  - job_name: 'configserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'configserver:8071' ]