apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationsdb-service-deployment
  labels:
    app: notificationsdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificationsdb
  template:
    metadata:
      labels:
        app: notificationsdb
    spec:
      containers:
        - name: notificationsdb
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: notificationsdb
            - name: MYSQL_USER
              value: notifications
            - name: MYSQL_PASSWORD
              value: "17052002"
          ports:
            - containerPort: 3306