deploymentName: eurekaserver-service-deployment
serviceName: eurekaserver
appLabel: eurekaserver
appName: eurekaserver

replicaCount: 1

image:
  repository: dannguyenmessi/forum-eureka-server
  tag: v1

containerPort: 8070

service:
  type: LoadBalancer
  port: 8070
  targetPort: 8070

appname_enabled: true
profile_enabled: false
config_enabled: true
resourceserver_enabled: false
oauth_openid_enabled: false
zipkin_enabled: true
kafka_enabled: false
minio_enabled: false
redis_enabled: false
pageniation_enabled: false
schedule_enabled: false
appBaseUrl_enabled: false
usersdb_enabled: false
postsdb_enabled: false
commentsdb_enabled: false
notificationsdb_enabled: false
reportsdb_enabled: false
redis_reactive_enabled: false