apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-service-deployment
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: dannguyenmessi/forum-minio:v1
          ports:
            - containerPort: 9000
            - containerPort: 9001
