apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-service-deployment
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: dannguyenmessi/keycloak:v1
          ports:
          - containerPort: 3100