apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      name: http
    - port: 9001
      targetPort: 9001
      name: http2