deploymentName: comments-service-deployment
serviceName: comments-service
appLabel: comments-service
appName: comments

replicaCount: 1

image:
  repository: dannguyenmessi/forum-comments
  tag: v1

containerPort: 9000

service:
  type: ClusterIP
  port: 9000
  targetPort: 9000

appname_enabled: true
profile_enabled: true
config_enabled: true
resourceserver_enabled: false
oauth_openid_enabled: false
zipkin_enabled: true
kafka_enabled: true
minio_enabled: true
redis_enabled: true
pageniation_enabled: true
schedule_enabled: true
appBaseUrl_enabled: true
usersdb_enabled: false
postsdb_enabled: false
commentsdb_enabled: true
notificationsdb_enabled: false
reportsdb_enabled: true
redis_reactive_enabled: false