global:
  configMapName: forumprod-configmap
  activeProfile: prod
  configServerURL: configserver:http://configserver:8071
  kubernetesDiscoveryServerURL: http://spring-cloud-kubernetes-discoveryserver:80/
  keyCloakJWKURL: http://keycloak:7080/auth/realms/forum/protocol/openid-connect/certs
  keyCloakOpenIdURL: keycloak:7080
  zipkinEndPoint: http://tempo-grafana-tempo-distributor:9411/api/v2/spans
  kafkaBrokerURL: kafka:9092
  minioRootUser: didannguyen
  minioRootPassword: "17052002"
  minioRootEndPoint: https://minio.forum.didan.id.vn
  redisCacheEnabled: true
  redisCacheHost: redis
  redisCachePort: 6379
  defaultPageSize: 20
  fixedDelayMilliseconds: 300000
  baseURL: https://api.forum.didan.id.vn/forum
  userDBURL: jdbc:mysql://usersdb:3308/usersdb
  userDBUsername: users
  userDBPassword: "17052002"
  postDBURL: jdbc:mysql://postsdb:3309/postsdb
  postDBUsername: posts
  postDBPassword: "17052002"
  commentDBURL: jdbc:mysql://commentsdb:3310/commentsdb
  commentDBUsername: comments
  commentDBPassword: "17052002"
  notificationDBURL: jdbc:mysql://notificationsdb:3311/notificationsdb
  notificationDBUsername: notifications
  notificationDBPassword: "17052002"
  reportDBURL: jdbc:mysql://reportsdb:3312/reportsdb
  reportDBUsername: reports
  reportDBPassword: "17052002"
  redisHost: redis
  redisPort: 6379
  lokiURL: http://loki-grafana-loki-gateway:80/loki/api/v1/push



