apiVersion: apps/v1
kind: Deployment
metadata:
  name: write-service-deployment
  labels:
    app: write
spec:
  replicas: 1
  selector:
    matchLabels:
      app: write
  template:
    metadata:
      labels:
        app: write
    spec:
      containers:
        - name: write
          image: dannguyenmessi/forum-write-loki:v1
          ports:
            - containerPort: 3100
            - containerPort: 9095
            - containerPort: 7946