apiVersion: v1
kind: Service
metadata:
  name: write
spec:
  selector:
    app: write
  type: ClusterIP
  ports:
    - port: 3102
      targetPort: 3100
      name: http
    - port: 9095
      targetPort: 9095
      name: http2
    - port: 7946
      targetPort: 7946
      name: http3