deploymentName: configserver-service-deployment
serviceName: configserver
appLabel: configserver
appName: configserver

replicaCount: 1

image:
  repository: dannguyenmessi/forum-configserver
  tag: v1

containerPort: 8071

service:
  type: LoadBalancer
  port: 8071
  targetPort: 8071

appname_enabled: true
profile_enabled: false
config_enabled: false
resourceserver_enabled: false
oauth_openid_enabled: false
zipkin_enabled: true
kafka_enabled: false
minio_enabled: false
redis_enabled: false
pageniation_enabled: false
schedule_enabled: false
appBaseUrl_enabled: false
usersdb_enabled: false
postsdb_enabled: false
commentsdb_enabled: false
notificationsdb_enabled: false
reportsdb_enabled: false
redis_reactive_enabled: false